### ISSUE TITLE
An unusual issue arising from the manner in which rules_python manages namespace packages.

### ISSUE THREAD

**Issue by Agent-Hellboy** [bazelbuild/rules_python#1886] opened 2024-05-07 11:34 UTC
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Hi,

I'm relatively new to Bazel and have only started using it a few days ago. I've gone through some introductory documentation.

In rules_python, I've noticed that it adds __init__.py files to every namespace package. I assume this is done to convert Python packages into Bazel packages with a BUILD file. However, I'm puzzled as to why it adds __init__.py to  namespace package.

Recently, I encountered an issue where an unnecessary __init__.py file was added. Specifically, it was added to python_local_deps_pyqt5/site-packages/PyQt5/uic/widget-plugins. I'm not sure why this was done, as it doesn't seem necessary.

PyQt5 dynamically loads these plugins at runtime using Python's exec API, which assumes a certain structure. Because of this, You can't simply add the __init__.py file without proper justification.

It seems that rules_python adds __init__.py files primarily to include a __path__ variable. However, I believe rules_python should only add __init__.py files when converting a package into a Bazel package.

If you have any insights into why rules_python behaves this way or how I can resolve the issue with the unnecessary __init__.py file, I would greatly appreciate your input. (I guess only way is to avoid adding __init__.py or i need to patch the load_plugin method of pyqt5 library)

## 🔬 Minimal Reproduction

Install PyQt5 as an external dependency using rules_python. Then, attempt to load a .ui file using uic. This process will require loading a plugin, which may result in an error.

## 🔥 Exception or Error

<pre><code>

 File "/var/tmp/proshan/c7b4a059b4e2be58/cpu/applications/bazel_output_base/execroot/cap/bazel-out/k8-opt-a3-bn_h10/bin/hwio/dma/scheduler/dma_scheduler.runfiles/python_local_deps_pyqt5/site-packages/PyQt5/uic/objcreator.py", line 158, in load_plugin
    raise WidgetPluginError("%s: %s" % (e.__class__, str(e)))
PyQt5.uic.exceptions.WidgetPluginError: <class 'NameError'>: name '__path__' is not defined

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux aws-devel-02 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 6.1.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
rules_python-0.31.0
  </code>
</pre>

**Anything else relevant?**

**Comment by aignas** [comment] 2024-05-13 03:04
I wrote about this in https://anikevicius.lt/blog/python-lazy-loading-and-namespace-pkgs/ and I am not sure if there is a good way to solve this other than have a single folder where we install all of the packages as part of a build action.

I know that @mattem is working a lot in this direction within `rules_py` but I doubt that there are any plans to contribute any of that work to `rules_python`.

My initial thinking would be to start looking into ways to make `uv` useful within `rules_python` for including the third party libraries, but I am not sure I'll have time in the nearest future to explore this here.

**Comment by rickeylev** [comment] 2024-05-13 05:26
The adding of `__init__.py` files is controlled by a flag and target-level setting. I forget their name atm. In any case, the basic way it works is a binary looks at all the files in runfiles, and adds any missing init.py files to directories containing .py or .so files.

Yes, this behavior is annoying and causes issues like the one described. We'd like to change this behavior, but it's a fairly large breaking change (the global flag is a large hammer that will work; the binary-level attribute works until another binary triggers the behavior), and haven't come up with a more incremental strategy.

> I assume this is done to convert Python packages into Bazel packages with a BUILD file

Sort of. It's mostly from how Bazel works internally at Google (adding empty files to every directory is tedious and gets mixed reception), and related to how to properly model `__init__.py` files given Bazel's dependency model (they cause circular dependencies / heavy weight dependencies)

**Comment by gedalia** [comment] 2024-08-09 12:38
I've hit something like this, using nvidia's omniverse and isaac sim libraries, enable_implicit_namespace_pkgs and seems to break the package. I've also found that I need to explicitly move the unpacked packages based on the contents of top_level.txt, and then mess with the sandbox. I'm on an older version of rules_python but I suspect things wouldn't be much different on a newer one.

**Comment by Agent-Hellboy** [comment] 2024-08-12 17:19
@gedalia I patched the method of the dependent library to avoid looking at the __init__.py, it's because of extra __init__.py ,  ignore it.

**Comment by groodt** [comment] 2024-08-24 10:55
I'm going to close this issue since it appears that the original poster has a workaround or solution.

For posterity, the bazel flag that @rickeylev mentions is: `--incompatible_default_to_explicit_init_py` which controls the creation of empty init.py files. See https://github.com/bazelbuild/bazel/issues/7386

Given that this issue relates to a third-party distribution package (PyQT5), it might actually be caused by the treatment that the rules_python whl_installer does to convert namespace packages to pkgutil namespaces. See https://github.com/bazelbuild/rules_python/blob/main/python/private/pypi/whl_installer/namespace_pkgs.py#L74

I think we might find that there are fewer issues with namespace packages if a `site-packages` layout is adopted by rules_python https://github.com/bazelbuild/rules_python/issues/2156

**Closed by groodt** 2024-08-24 10:55 UTC
Labels: type: feature request, help wanted, type: pip
