### ISSUE TITLE
pip dependencies name conflict

### ISSUE THREAD

**Issue by liuyl** [bazelbuild/rules_python#275] opened 2020-01-27 22:27 UTC
Consider a `py_binary` target has 
```
deps = [
    requirement("google-auth"),
    requirement("google-cloud-storage")
]
```

Both `google-auth` and `google-cloud-storage` package have top level directory `google`, which causes conflict. 
`import google.storage` will complain about no module named `google.storage` because python is trying to find `storage` module in the `google-auth` package's `google` directory.

Wonder has anybody else had this issue, and how to resolve it?

**Comment by thundergolfer** [comment] 2020-01-27 22:42
This is a duplicate of https://github.com/bazelbuild/rules_python/issues/65. Yep, a lot of us have had this issue 😅. It's also a problem for the `azure.*` packages (https://github.com/bazelbuild/rules_python/issues/273, https://github.com/bazelbuild/rules_python/issues/93). 

These are long standing issues, so we fixed out problem over in https://github.com/dillon-giacoppo/rules_python_external and now use that at work.

**Comment by thundergolfer** [comment] 2020-01-27 22:43
There's also https://github.com/ali5h/rules_pip and https://github.com/apt-itude/rules_pip which I think also handle this problem. The latter might not be actively maintained though.

**Comment by liuyl** [comment] 2020-01-29 16:30
@thundergolfer indeed, thanks for the pointer to other related bugs and the solution! will try rules_python_external.

**Comment by thundergolfer** [comment] 2020-06-14 12:55
Closing as duplicate of https://github.com/bazelbuild/rules_python/issues/93 and https://github.com/bazelbuild/rules_python/issues/65

**Closed by thundergolfer** 2020-06-14 12:55 UTC
