### ISSUE TITLE
Unable to compile standalone gazelle binary with rules_python plugin

### ISSUE THREAD

**Issue by Whoaa512** [bazelbuild/rules_python#1455] opened 2023-10-03 23:48 UTC
Context:
I work within a repo where we require building a static gazelle binary per platform that is checked into git LFS. The precompiled binaries are then used for pre-commit hooks and can be run in CI environments without the need to build from source with bazel.

Issue:
I'm having issues compiling gazelle with the rules_python package because it makes use of runfiles.

The runfiles however is not portable and short of patching the [parser.go](https://github.com/bazelbuild/rules_python/blob/9eccb7943f012b4b20c57107bc40e7cdeccbc145/gazelle/python/parser.go#L47) I don't see a clear path to compiling this gazelle plugin to be a portable go binary.

Is this intentional or could there be an alternative that allows for this?

**Comment by aignas** [comment] 2023-10-04 00:20
The gazelle plugin depends on a python interpreter and a few python files that are executed using the said interpreter, so creating a standalone binary would not be possible.

The fact that gazelle needs to:
1. Parse the python imports and
2. Understand what imports are from stdlib

makes it very difficult to achieve without having a Python interpreter.

**Comment by aignas** [comment] 2023-10-04 23:14
Just to add here what has been discussed over Slack, https://github.com/kluctl/go-embed-python seems to be like an interesting way to embed the Python interpreter into a go binary and we could potentially use this project to include our own Python toolchain.

**Comment by groodt** [comment] 2023-10-09 22:57
Possible duplicate of https://github.com/bazelbuild/rules_python/issues/691
(or, at very least, related to it)

**Comment by aignas** [comment] 2023-10-15 23:47
#1485 Should fix the `single binary` part of the issue, but it would still need system python, which needs to be addressed via #691.

**Closed** 2023-10-17 05:13 UTC

**Comment by Whoaa512** [comment] 2023-10-17 06:44
Thank you! This is perfect for my needs. Agree that #691 needs to be addressed but this will remove the need for a genrule where I basically create a runfiles dir next to my pre-compiled gazelle.

Cheers!
