### ISSUE TITLE
Cross Platform wheel dependencies

### ISSUE THREAD

**Issue by 0xflick** [bazelbuild/rules_python#2234] opened 2024-09-19 19:28 UTC
I'm having some trouble building a cross platform py_binary (building for linux_aarch64 on a m series mac) for use inside a docker container. I'm able to get a simple hello world running, however if I depend on a pip package with a platform specific distributions I'm unable to figure out how to download a dependency for anything other than the current host platform.

I'm able to partially work around this by building inside a docker container, but I was wondering if I'm simply missing something.

**Comment by 0xflick** [comment] 2024-09-19 20:41
I was able to temporarily get this to work by forcing wheel_installer to install the manylinux version. However, I can't seem to get `extra_pip_args` to propagate from `pip.parse(...)` to the downloader. Is there a longer term fix here? Or should I stick with building from the target platform

**Comment by groodt** [comment] 2024-09-21 04:04
Closing as a duplicate of https://github.com/bazelbuild/rules_python/issues/260

This isn't well supported at the moment. There are some experimental flags you can try. See the issue for some details.

**Closed by groodt** 2024-09-21 04:04 UTC
