### ISSUE TITLE
rules_python doesn't read dependencies from METADATA files

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_python#70] opened 2018-02-27 16:39 UTC
This means that rules that depend (directly or indirectly) on wheels that don't contain `metadata.json` (eg [celery==3.1.11](https://pypi.python.org/pypi/celery/3.1.11)), will fail as described in [this message to bazel-discuss](https://groups.google.com/d/msg/bazel-discuss/Nt4F-_4vmJc/hOd0_EdEAQAJ).

The cause appears to be [this TODO](https://github.com/bazelbuild/rules_python/blob/115e3a0dab4291184fdcb0d4e564a0328364571a/rules_python/whl.py#L110):
```
# TODO: handle fields other than just name
```

This can be worked around by manually declaring the dependencies in requirements.txt and your own rules.

**Comment by drigz** [comment] 2018-06-04 10:18
This is likely to become more pressing since wheel v0.31.0 stopped generating metadata.json. google-auth versions after 1.4.1 don't have metadata.json, so you either have to pin to 1.4.1 or manually declare the dependencies.

https://github.com/pypa/wheel/blob/3dc261abc98a5e43bc7fcf5783d080aaf8f9f0cf/CHANGES.txt#L13

**Comment by evanj** [comment] 2018-06-04 13:10
My pull request #90 is an attempt to resolve this. I haven't tested it extremely carefully, but so far this patch has worked for the packages we use.

**Comment by brandjon** [comment] 2018-11-13 18:03
FTR this issue is the cause of #98.

**Comment by brandjon** [comment] 2018-11-13 18:47
Prioritizing because this can easily cause annoying breakages as shown by #98. Will look at this after other CI failures / blockers.

**Comment by thundergolfer** [comment] 2021-04-13 13:37
No longer a problem with `pip_install` repo rule. Closing issue.

**Closed by thundergolfer** 2021-04-13 13:37 UTC
Labels: P2, type: bug
