### ISSUE TITLE
Problem handling namespace packages with circular dependencies in Airflow 2

### ISSUE THREAD

**Issue by gvacaliuc** [bazelbuild/rules_python#411] opened 2021-01-31 20:26 UTC
I'm not sure if this is technically a bug with rules_python, but I've run into some trouble installing airflow 2.  I thought I would open here for advice and to surface the issue for others.

Example repo to repro the failure: https://github.com/gvacaliuc/rules_python_airflow2

The `apache-airflow` pypi package now depends on a few other small namespace packages which in turn depend on `apache-airflow`.  [pip apparently resolves](https://github.com/apache/airflow/issues/12744#issuecomment-738027087) this cyclic dependency, but rules_python produces an invalid library structure:

```
gvacaliuc@chiron:~/.../gvacaliuc/rules_python_airflow2$ cat /home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/85385b6bcbbb23d240857dfefd8684dd/external/py_deps/pypi__apache_airflow/BUILD 
package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pypi__apache_airflow",
    srcs = glob(["**/*.py"], allow_empty = True),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = ["//pypi__alembic","//pypi__apache_airflow_providers_ftp","//pypi__apache_airflow_providers_http","//pypi__apache_airflow_providers_imap","//pypi__apache_airflow_providers_sqlite","//pypi__argcomplete","//pypi__attrs","//pypi__cached_property","//pypi__cattrs","//pypi__colorlog","//pypi__connexion","//pypi__croniter","//pypi__cryptography","//pypi__dill","//pypi__flask","//pypi__flask_appbuilder","//pypi__flask_caching","//pypi__flask_login","//pypi__flask_swagger","//pypi__flask_wtf","//pypi__funcsigs","//pypi__graphviz","//pypi__gunicorn","//pypi__importlib_metadata","//pypi__importlib_resources","//pypi__iso8601","//pypi__itsdangerous","//pypi__jinja2","//pypi__json_merge_patch","//pypi__jsonschema","//pypi__lazy_object_proxy","//pypi__lockfile","//pypi__markdown","//pypi__markupsafe","//pypi__marshmallow_oneofschema","//pypi__pandas","//pypi__pendulum","//pypi__psutil","//pypi__pygments","//pypi__python_daemon","//pypi__python_dateutil","//pypi__python_nvd3","//pypi__python_slugify","//pypi__requests","//pypi__rich","//pypi__setproctitle","//pypi__sqlalchemy","//pypi__sqlalchemy_jsonfield","//pypi__tabulate","//pypi__tenacity","//pypi__termcolor","//pypi__thrift","//pypi__tzlocal","//pypi__unicodecsv","//pypi__urllib3","//pypi__werkzeug"],
)
gvacaliuc@chiron:~/.../gvacaliuc/rules_python_airflow2$ cat /home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/85385b6bcbbb23d240857dfefd8684dd/external/py_deps/pypi__apache_airflow_providers_sqlite/BUILD 
package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "pypi__apache_airflow_providers_sqlite",
    srcs = glob(["**/*.py"], allow_empty = True),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = ["//pypi__apache_airflow"],
)
```

Resulting in the build failure:
```
gvacaliuc@chiron:~/.../gvacaliuc/rules_python_airflow2$ bazelisk build :main 
ERROR: /home/gvacaliuc/.cache/bazel/_bazel_gvacaliuc/85385b6bcbbb23d240857dfefd8684dd/external/py_deps/pypi__apache_airflow/BUILD:5:1: in py_library rule @py_deps//pypi__apache_airflow:pypi__apache_airflow: cycle in dependency graph:
    //:main
.-> @py_deps//pypi__apache_airflow:pypi__apache_airflow
|   @py_deps//pypi__apache_airflow_providers_sqlite:pypi__apache_airflow_providers_sqlite
`-- @py_deps//pypi__apache_airflow:pypi__apache_airflow
This cycle occurred because of a configuration option
ERROR: Analysis of target '//:main' failed; build aborted
INFO: Elapsed time: 0.159s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

In **this** case, it seems like we'd want to merge the contents of the airflow provider wheels with the main airflow wheel before generating the build files?

**Comment by thundergolfer** [comment] 2021-02-03 06:52
Ahhh interesting. Thanks for the reproduction, I was able to clone and reproduce.

In a way this is exactly what Bazel is supposed to do: detect circular dependencies. 

I'd want to understood why `pip` allows this and how widespread these circular setups are. From a quick googling I didn't find much. 

This comment in the Airflow repo is odd. Seems to contradict what we're seeing: 

```
# Those providers are pre-installed always when airflow is installed.
# Those providers do not have dependency on airflow2.0 because that would lead to circular dependencies.
# This is not a problem for PIP but some tools (pipdeptree) show those as a warning.
PREINSTALLED_PROVIDERS = [
    'ftp',
    'http',
    'imap',
    'sqlite',
] 
```
[apache/airflow/blob/0e8c77b93a5ca5ecfdcd1c4bd91f54846fc15d57/setup.py#L793](https://github.com/apache/airflow/blob/0e8c77b93a5ca5ecfdcd1c4bd91f54846fc15d57/setup.py#L793)

**Comment by groodt** [comment] 2021-02-03 07:44
`airflow` is one of these fairly large kitchen-sink packages that causes older and more incorrect versions of pip to have issues.

```
/tmp/airflow2
❯ python --version
Python 3.8.6

/tmp/airflow2
❯ python -m venv .venv

/tmp/airflow2
❯ source ./.venv/bin/activate.fish

/tmp/airflow2
.venv ❯ pip --version
pip 20.2.1 from /private/tmp/airflow2/.venv/lib/python3.8/site-packages/pip (python 3.8)

/tmp/airflow2
.venv ❯ pip install wheel pipdeptree
Requirement already satisfied: wheel in ./.venv/lib/python3.8/site-packages (0.36.2)
Requirement already satisfied: pipdeptree in ./.venv/lib/python3.8/site-packages (2.0.0)
Requirement already satisfied: pip>=6.0.0 in ./.venv/lib/python3.8/site-packages (from pipdeptree) (20.2.1)
WARNING: You are using pip version 20.2.1; however, version 21.0.1 is available.
You should consider upgrading via the '/private/tmp/airflow2/.venv/bin/python -m pip install --upgrade pip' command.

/tmp/airflow2
.venv ❯ cat requirements.txt
apache-airflow==2.0.0

...

/tmp/airflow2
.venv ❯ pipdeptree
Warning!! Cyclic dependencies found:
* apache-airflow-providers-sqlite => apache-airflow => apache-airflow-providers-sqlite
* apache-airflow-providers-imap => apache-airflow => apache-airflow-providers-imap
* apache-airflow-providers-http => apache-airflow => apache-airflow-providers-http
* apache-airflow-providers-ftp => apache-airflow => apache-airflow-providers-ftp
* apache-airflow => apache-airflow-providers-ftp => apache-airflow
* apache-airflow => apache-airflow-providers-http => apache-airflow
* apache-airflow => apache-airflow-providers-imap => apache-airflow
* apache-airflow => apache-airflow-providers-sqlite => apache-airflow
------------------------------------------------------------------------
pipdeptree==2.0.0
  - pip [required: >=6.0.0, installed: 20.2.1]
swagger-ui-bundle==0.0.8
  - Jinja2 [required: >=2.0, installed: 2.11.3]
    - MarkupSafe [required: >=0.23, installed: 1.1.1]
wheel==0.36.2
```

There is definitely a circular dependency in the wheel:
```
/tmp/airflow2
.venv ❯ cat apache_airflow_providers_ftp-1.0.0.dist-info/METADATA
Metadata-Version: 2.1
Name: apache-airflow-providers-ftp
Version: 1.0.0
Summary: Provider package apache-airflow-providers-ftp for Apache Airflow
Home-page: http://airflow.apache.org/
Author: Apache Software Foundation
Author-email: dev@airflow.apache.org
License: Apache License 2.0
Download-URL: https://archive.apache.org/dist/airflow/providers
Project-URL: Documentation, https://airflow.apache.org/docs/
Project-URL: Bug Tracker, https://github.com/apache/airflow/issues
Project-URL: Source Code, https://github.com/apache/airflow
Platform: UNKNOWN
Classifier: Development Status :: 5 - Production/Stable
Classifier: Environment :: Console
Classifier: Environment :: Web Environment
Classifier: Intended Audience :: Developers
Classifier: Intended Audience :: System Administrators
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Topic :: System :: Monitoring
Requires-Python: ~=3.6
Description-Content-Type: text/markdown
**Requires-Dist: apache-airflow (>=2.0.0a0)**
```

**Comment by thundergolfer** [comment] 2021-02-05 01:11
@groodt what do you make of their comment in the `setup.py`? 

> # Those [sic] providers do not have dependency on airflow2.0 because that would lead to circular dependencies.

Are they mistaken, or is there some specific context in which they don't have the dependency, but for our intents and purposes they do have a dependency on `airflow2.0`

**Comment by groodt** [comment] 2021-02-05 03:16
They are mistaken. Whether or not it's a bug or not, I'm not sure. They have a complex `setup.py` and whatever came out of that code produced a wheel on pypi that includes `Requires-Dist: apache-airflow`

**Comment by thundergolfer** [comment] 2021-02-08 23:23
@gvacaliuc over in [that linked Airflow issue](https://github.com/apache/airflow/issues/14128) an Airflow maintainer has informed me that an upcoming release of the providers (1.1.0) won't have this issue.

I'll close this issue as not a bug in rules_python 

👍

**Closed** 2021-02-08 23:23 UTC

**Comment by gvacaliuc** [comment] 2021-02-10 16:02
Thanks!
