### ISSUE TITLE
rules_python build_file_generation integration tests on Ubuntu using minimum supported Bazel version is failing with "requirements_test on Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1520] opened 2023-10-30 07:04 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3423#018b7e52-e06d-4e38-8577-97686d10d343

Platform : [rules_python (build_file_generation integration tests on Ubuntu)](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3423#018b7e52-e06d-4e38-8577-97686d10d343)

Logs:
```

(02:05:20) FAIL: //:requirements_test (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6a1011ee018bdbf38289288c626fc42e/execroot/_main/bazel-out/k8-fastbuild/testlogs/requirements_test/test.log)
 
FAILED: //:requirements_test (Summary)
```

Steps:
```
git clone -v https://github.com/bazelbuild/rules_python.git
git reset 5b082bb02b048a4b630843b6b582bd6f40d38b9e --hard
export USE_BAZEL_VERSION=8cab6aa21fa765985a962e59264e12251e4d479f
bazel test -- ...
```
Autosheriff culprit : https://github.com/bazelbuild/bazel/commit/32cc97e0a9a5810ab5469708f768666022c27642

CC Greenteam @comius

**Comment by rickeylev** [comment] 2023-10-30 21:49
qq: did the system python version change on the build hosts? i.e. from python 3.8 to python 3.9? That looks to be a common diff showing up. (I'm not asking to undo that, it would just explain why this failure shows up).

PR 1522 it out to partially address this -- many of those tests are trying to run bazel at head for the configs that should only be running Bazel 5.4. That will, at the least, skip those configs where it doesn't need to run.

I'm still looking into the root cause.

**Comment by rickeylev** [comment] 2023-10-30 21:59
Ah, I think this is because of switching bzlmod on by default. Setting `--noenable_bzlmod` when running some of the failing tests fixes it.

**Comment by rickeylev** [comment] 2023-10-31 22:09
Ok, I think I have PRs out for all the failures shown in that link. They're all fairly simple fixes. Most just need a MODULE.bazel file, a couple needed to change how they were finding files in runfiles.

**Comment by rickeylev** [comment] 2023-11-01 16:00
All the PRs are merged. I think that fixes all the failures. @sgowroji let us know if more failures show up in subsequent downstream bazel runs

**Comment by sgowroji** [comment] 2023-11-06 05:04
Hi @rickeylev, Rules_Python is still failing with below errors with Bazel@HEAD.
[build_file_generation integration tests on Ubuntu](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3440#018ba25e-7f17-48a3-9550-9b13caee289c)
 [example bzlmod build file integration test](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3440#018ba25e-7f31-47ce-90a2-9f06df0ca176)
 [pip_repository_annotations integration tests on Ubuntu](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3440#018ba25e-7f5b-4af3-a871-55992f6bff1c)

**Comment by rickeylev** [comment] 2023-11-06 22:10
Thanks. Looks like the same cause: bzlmod enabled by default.

**Comment by rickeylev** [comment] 2023-11-07 22:42
Ok, all PRs merged. Fixed :crossed_fingers:

**Closed by rickeylev** 2023-11-07 22:42 UTC
