### ISSUE TITLE
Does not gracefully handle dependencies with invalid characters in file names

### ISSUE THREAD

**Issue by marczych** [bazelbuild/rules_python#75] opened 2018-03-16 20:55 UTC
I added `pyfiglet==0.7.5` to the `requirements.txt` loaded by `pip_import` which made the rules explode because of this file name in the pyfiglet package: `pyfiglet/fonts/ripper!_.flf`:

```
ERROR: /home/marc.zych/.cache/bazel/_bazel_marc.zych/45ba23047e061ecba1878da72758f36b/external/pypi__pyfiglet_0_7_5/BUILD:6:1: @pypi__pyfiglet_0_7_5//:pkg: invalid label 'pyfiglet/fonts/ripper!_.flf' in element 370 of attribute 'data' in 'py_library' rule: invalid target
name 'pyfiglet/fonts/ripper!_.flf': target names may not contain '!'
ERROR: /home/marc.zych/.cache/bazel/_bazel_marc.zych/45ba23047e061ecba1878da72758f36b/external/pypi__pyfiglet_0_7_5/BUILD:6:1: Target '@pypi__pyfiglet_0_7_5//:pyfiglet/__init__.py' contains an error and its package is in error and referenced by '@pypi__pyfiglet_0_7_5//:pk
g'
ERROR: /home/marc.zych/.cache/bazel/_bazel_marc.zych/45ba23047e061ecba1878da72758f36b/external/pypi__pyfiglet_0_7_5/BUILD:6:1: Target '@pypi__pyfiglet_0_7_5//:pyfiglet/__main__.py' contains an error and its package is in error and referenced by '@pypi__pyfiglet_0_7_5//:pk
g'
ERROR: /home/marc.zych/.cache/bazel/_bazel_marc.zych/45ba23047e061ecba1878da72758f36b/external/pypi__pyfiglet_0_7_5/BUILD:6:1: Target '@pypi__pyfiglet_0_7_5//:pyfiglet/fonts/__init__.py' contains an error and its package is in error and referenced by '@pypi__pyfiglet_0_7_
5//:pkg'
ERROR: /home/marc.zych/.cache/bazel/_bazel_marc.zych/45ba23047e061ecba1878da72758f36b/external/pypi__pyfiglet_0_7_5/BUILD:6:1: Target '@pypi__pyfiglet_0_7_5//:pyfiglet/test.py' contains an error and its package is in error and referenced by '@pypi__pyfiglet_0_7_5//:pkg'
ERROR: /home/marc.zych/.cache/bazel/_bazel_marc.zych/45ba23047e061ecba1878da72758f36b/external/pypi__pyfiglet_0_7_5/BUILD:6:1: Target '@pypi__pyfiglet_0_7_5//:pyfiglet/version.py' contains an error and its package is in error and referenced by '@pypi__pyfiglet_0_7_5//:pkg
'
ERROR: /home/marc.zych/code/driving/experimental/marczych/rules_python/BUILD:6:1: Target '@pypi__pyfiglet_0_7_5//:pkg' contains an error and its package is in error and referenced by '//experimental/marczych/rules_python:rules_python_test'
ERROR: Analysis of target '//experimental/marczych/rules_python:rules_python_test' failed; build aborted: Loading failed
INFO: Elapsed time: 9.000s
FAILED: Build did NOT complete successfully (6 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

This is likely a pyfiglet or Bazel issue but I don't think that either of them would fix it which is why I'm soliciting help here. Is there any workaround for this?

**Comment by shelman** [comment] 2018-07-27 14:43
I am seeing this same issue when using `mr.bob` as a dependency:
```
ERROR: /private/var/tmp/_bazel_shelman/16085b930c3d11ea5082bcd385f2a362/external/pypi__mr_bob_0_1_2/BUILD:6:1: @pypi__mr_bob_0_1_2//:pkg: invalid label 'mrbob/tests/templates/encodingč/mapča/ća.bob' in element 25 of attribute 'data' in 'py_library' rule: invalid target name 'mrbob/tests/templates/encodingč/mapča/ća.bob': target names may not contain non-printable characters: '\x8C'
```

Is there a recommended workaround? Or a fix in the works?

**Comment by lberki** [comment] 2018-07-30 08:18
Adding @brandjon and @dslomov (the latter, because this is a special case of our old "labels cannot contain any character" limitation)

**Comment by thundergolfer** [comment] 2021-03-02 08:51
Testing with Bazel `4.0.0` and the latest release of rules_python, 0.1.0, pyfiglet==0.7.5 works fine. 

Reproduction repository here: https://github.com/thundergolfer-playground/rules_python_issue_75_reproduction

On the basis of that working reproduction, I'll close this issue 👍

**Closed by thundergolfer** 2021-03-02 08:51 UTC
Labels: untriaged
