### ISSUE TITLE
Modify import path of pip package imported via "requirement()"

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/rules_python#356] opened 2020-09-07 09:11 UTC
Hi,

I'm using `rules_python` to import pip packages required for my py_binary application.

So far so good, but I run into an issue when importing `tensorflow` - my `py_binary` cannot import it.
The reason is that the tensorflow.whl file contains this folder structure:

`/folder1/folder2/tensorflow/__init__.py`
Instead of what rules_python expects/assumes:

`/tensorflow/__init__.py`

I would like to be able to append `folder1/folder2` to the tensorflow path that is added to PYTHONPATH, in order to be able to import it. Similar to the `imports` option in `py_library`.

Is this supported?

The only alternative solution is to import the TensorFlow Bazel workspace and build from source, but it is unnecessary and will take long time to build.

Related issue: https://github.com/tensorflow/tensorflow/issues/21461

Thanks!

**Comment by thundergolfer** [comment] 2020-09-07 10:24
@carlosgalvezp I think this is a duplicate of https://github.com/bazelbuild/rules_python/issues/71, and I see you've commented already in that issue. I've given an update there, which is hopefully sufficient. 

Closing as duplicate.

**Closed by thundergolfer** 2020-09-07 10:24 UTC

**Comment by carlosgalvezp** [comment] 2020-09-07 10:43
Thanks, indeed it's a duplicate, sorry about that! Will try your suggestion on the other issue :)
