### ISSUE TITLE
Wrong deps labels from Python Gazelle when trying examples/build_file_generation

### ISSUE THREAD

**Issue by loquatv2** [bazelbuild/rules_python#956] opened 2022-12-30 05:34 UTC
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: Python Gazelle plugin

### Is this a regression?

 n/a

### Description

 
Running the example in [examples/build_file_generation](https://github.com/bazelbuild/rules_python/tree/main/examples/build_file_generation) results in error "no such package '@pip//pypi__flask'". Might be a bug from the `pip_install` to `pip_parse` migration?

## 🔬 Minimal Reproduction

Just copy the [examples/build_file_generation](https://github.com/bazelbuild/rules_python/tree/main/examples/build_file_generation) directory and run the example. Then `bazel build :build_file_generation`

## 🔥 Exception or Error

<pre><code>

ERROR: /my_directory/BUILD.bazel:64:11: no such package '@pip//pypi__flask': BUILD file not found in directory 'pypi__flask' of external repository @pip. Add a BUILD file to a directory to mark it as a package. and referenced by '//:build_file_generation'

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 13.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 6.0.0-homebrew
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
rules_python-0.16.1
  </code>
</pre>

**Anything else relevant?**

https://github.com/bazelbuild/rules_python#using-third_party-packages-as-dependencies says

```
For pip_install the labels are instead of the form

@{name}//pypi__{package}
```

In [examples/build_file_generation](https://github.com/bazelbuild/rules_python/tree/main/examples/build_file_generation), `pip_parse` is used but still the labels are of the above form for `pip_install`. Manually changing it to `requirement(xyz)` or `@{name}_{package}//:pkg` resolves the issue.

**Comment by groodt** [comment] 2022-12-30 06:12
Thanks for the report. I was unable to reproduce this on my side.

I think the issue may already be fixed in a recently merged PR. Can you please try the latest commit on `main`. If you are able to reproduce from the latest commit, then please create a repository that demonstrates the issue.

If the latest version on `main` does work for you, please close this issue. 😄

**Comment by loquatv2** [comment] 2022-12-30 06:33
Thanks Greg for the quick reply. Just tried the latest commit on `main` and can verify it's already fixed.

**Closed** 2022-12-30 06:34 UTC
