### ISSUE TITLE
Error: file '@rules_python//python:pip.bzl' does not contain symbol 'pip_install'

### ISSUE THREAD

**Issue by danbosnichill** [bazelbuild/rules_python#437] opened 2021-03-20 00:26 UTC
# 🐞 bug report

### Affected Rule

`@rules_python//python:pip.bzl`

### Is this a regression?

I don't know if this is a regression.  This is my first time integrating.

### Description

I'm trying to load the `pip_install` rule and it's failing.

## 🔬 Minimal Reproduction

Here is my WORKSPACE file:

<pre><code>
workspace(name = "schema")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.23.3/rules_go-v0.23.3.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.23.3/rules_go-v0.23.3.tar.gz",
    ],
    sha256 = "a8d6b1b354d371a646d2f7927319974e0f9e52f73a2452d2b3877118169eb6bb",
)

http_archive(
    name = "bazel_gazelle",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
    ],
    sha256 = "d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10",
)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.14.0",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.14.0.tar.gz"],
    sha256 = "d0f5f605d0d656007ce6c8b5a82df3037e1d8fe8b121ed42e536f569dec16113",
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_repository(
    name = "org_golang_google_protobuf",
    importpath = "google.golang.org/protobuf",
    sum = "h1:+Z5KGCizgyZCbGh1KZqA0fcLLkwbsjIzS4aV2v7wJX0=",
    version = "v1.4.2",
)

# Autogenerated rules.
# Run the following command to update the dependencies.
# bazel run //:gazelle -- update
gazelle_dependencies()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_proto_grpc",
    sha256 = "fa7a59e0d1527ac69be652407b457ba1cb40700752a3ee6cc2dd25d9cb28bb1a",
    strip_prefix = "rules_proto_grpc-3.1.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/3.1.0.tar.gz"],
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_repos")
rules_proto_grpc_toolchains()
rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos = "python_repos")
rules_proto_grpc_python_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "rules_proto_grpc_py3_deps",
    python_interpreter = "python3",
    requirements = "@rules_proto_grpc//python:requirements.txt",
)
</code></pre>

## 🔥 Exception or Error

I'm getting the following error
<pre><code>
ERROR: Traceback (most recent call last):
	File "/Users/me/dir/schema/WORKSPACE", line 84, column 40, in <toplevel>
		load("@rules_python//python:pip.bzl", "pip_install")
Error: file '@rules_python//python:pip.bzl' does not contain symbol 'pip_install'
ERROR: error loading package 'external': Package 'external' contains errors
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Mac OS v11.1.
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
❯ bazel version
Build label: 3.7.2-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 21:58:16 2020 (1608242296)
Build timestamp: 1608242296
Build timestamp as int: 1608242296
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.1.0
  </code>
</pre>

**Anything else relevant?**

Nope.

**Comment by hrfuller** [comment] 2021-03-21 01:18
Are there any other errors above the one you posted? The macro is defined https://github.com/bazelbuild/rules_python/blob/master/python/pip.bzl#L19

If you check in `bazel info output_base`/external/rules_python/ did the repo get downloaded correctly?

**Comment by depthwise** [comment] 2021-03-24 20:44
I'm experiencing a similar issue due to conflict with `rules_docker`.

**Comment by depthwise** [comment] 2021-03-24 20:58
GRPC, which OP uses, also seems to install its own packages. Could be a similar issue.

**Comment by depthwise** [comment] 2021-03-25 01:12
Putting `rules_python` ahead of all other rules in WORKSPACE fixed this issue for me. Sucks that it's order dependent though, ideally it shouldn't be.

**Comment by thundergolfer** [comment] 2021-03-28 23:48
Which version of rules_docker are you using? Past versions of `rules_docker` will certainly load an old version of `rules_python` which doesn't have `pip_install` which could explain why moving the `rules_python` 'up' fixes things for you.

**Comment by elasticdog** [comment] 2021-03-29 19:22
I was hitting a similar order dependent issue due to `com_google_protobuf` (pulled in for [Buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier)) once I added `io_bazel_rules_docker`. The most recent `rules_docker` release has been fixed:

https://github.com/bazelbuild/rules_docker/blob/v0.16.0/repositories/py_repositories.bzl#L22

...but protobuf currently pulls in an older version of `rules_python` (commit 4b84ad270387a7c439ebdccfd530e2339601ef27):

https://github.com/protocolbuffers/protobuf/blob/v3.15.6/protobuf_deps.bzl#L59

Since `protobuf_deps.bzl` has the conditional to check for an existing `rules_python`, I was able to fix the incompatibility issue by explicitly downloading the [`0.1.0` release](https://github.com/bazelbuild/rules_python/releases/tag/0.1.0) in my `WORKSPACE` before calling `protobuf_deps()`:

```starlark
http_archive(
    name = "rules_python",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz"],
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
)
```

**Comment by thundergolfer** [comment] 2021-04-19 03:33
@elasticdog yeah this is to my knowledge the best fix, unfortunately. This behavior is a consequence of the implementation of external repository resolution in the WORKSPACE, and not a rules_python bug. 

We should send an update to that rules_python load in https://github.com/protocolbuffers/protobuf as it hasn't been updated in ~2 years.

I think I can close this issue though, as it's not a bug in rules_python 👍.

**Closed by thundergolfer** 2021-04-19 03:33 UTC
