### ISSUE TITLE
Migrate to Bzlmod for managing external dependencies

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_python#1469] opened 2023-10-06 14:00 UTC
With future Bazel LTS versions, Bzlmod will become the default system for external dependencies management.

Please consider migrating all your external dependencies in WORKSPACE to MODULE.bazel

For more information, please check https://github.com/bazelbuild/bazel/issues/18958

**Comment by meteorcloudy** [comment] 2023-10-06 14:38
Some tests are still failing with Bzlmod enabled:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3352#018af628-22bd-468d-8813-0356ebe78c86

**Comment by rickeylev** [comment] 2023-10-06 20:22
posterity: From a cursory look, I get the impression the cause is some tests aren't going through the runfiles apis, so end up not being aware of repo-remapping.

**Comment by rickeylev** [comment] 2023-10-10 20:52
PR #1482 out to fix this. It's as I thought -- the runfiles directory changing to `_main` broke various assumptions.

**Comment by rickeylev** [comment] 2023-10-11 22:37
1482 is merged, so this should be fixed now

**Closed** 2023-10-18 02:42 UTC
