### ISSUE TITLE
Cannot depend on apache-airflow with extras (e.g. [kubernetes] or [postgres,statsd,kubernetes] )

### ISSUE THREAD

**Issue by thekyz** [bazelbuild/rules_python#439] opened 2021-03-24 09:43 UTC
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: pip_install

### Is this a regression?

Tried on older versions, issue was there already.

### Description

Cannot install apache-airflow

## 🔬 Minimal Reproduction

Code available in the repo here: https://github.com/thekyz/snippets/tree/master/rule_python_issue_with_apache-airflow

Specifically the issue is with the requirement function in here : https://github.com/thekyz/snippets/blob/b34ef1b6dcd54c26a698b0286edaed165ec4a872/rule_python_issue_with_apache-airflow/BUILD#L31

```
py_binary(
    name = "hello",
    srcs = [
        "hello.py",
    ],
    deps = [
        requirement("apache-airflow[postgres,statsd,kubernetes]"),
    ],
)
```

## 🔥 Exception or Error

```
ERROR: /home/thekyz/dev/snippets/rule_python_issue_with_apache-airflow/BUILD:25:10: no such package '@pip//pypi__apache_airflow[postgres,statsd,kubernetes]': BUILD file not found in directory 'pypi__apache_airflow[postgres,statsd,kubernetes]' of external repository @pip. Add a BUILD file to a directory to mark it as a package. and referenced by '//:hello'
```

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**Output of `bazel version`:**

```
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
```

**Rules_python version:**

0.1.0, tried with master as well, same issue

**Anything else relevant?**

If I get rid of the extras in the BUILD file requirement (replace `requirement("apache-airflow[postgres,statsd,kubernetes]")` with `requirement("apache-airflow") I get this instead:

```
ERROR: /home/thekyz/.cache/bazel/_bazel_thekyz/1db85497883e553a1d95bd5ce881c422/external/pip/pypi__apache_airflow/BUILD:5:11: in py_library rule @pip//pypi__apache_airflow:pypi__apache_airflow: cycle in dependency graph:
    //:hello
.-> @pip//pypi__apache_airflow:pypi__apache_airflow
|   @pip//pypi__apache_airflow_providers_cncf_kubernetes:pypi__apache_airflow_providers_cncf_kubernetes
`-- @pip//pypi__apache_airflow:pypi__apache_airflow
```

**Comment by thundergolfer** [comment] 2021-03-31 03:44
Thanks for the issue report, and thanks for doing the reproduction.

Firstly, you don't need to do `requirement("apache-airflow[postgres,statsd,kubernetes]")`. Once the extras are specified in the requirements file they'll be downloaded and included in `requirement("apache-airflow")`.

The circular dependencies issue is https://github.com/bazelbuild/rules_python/issues/411. I determined that this was an error in Airflow and a maintainer communicated that it would be fixed in an upcoming release.

Can you check out https://github.com/apache/airflow/issues/14128#issuecomment-775529495 and confirm this fixes your problem?

For now I'll close this as a duplicate of #411. If this turns out to be incorrect then happy to re-open and take another look.

**Closed by thundergolfer** 2021-03-31 03:44 UTC

**Comment by thundergolfer** [comment] 2021-04-01 03:36
Oh thanks for that heads up.
