### ISSUE TITLE
Create Python Provider

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_python#294] opened 2020-04-19 20:18 UTC
The idea would be to create a Python Runtime Provider.
Using this Python Runtime Provider you could then feed the interpreter and all files necessary to `py_runtime`.

This way people could build/fetch their own Python via a rule.
At the same time there is no need to standardize this in rules_python.

**Comment by dayfine** [comment] 2020-04-26 04:06
I think this is already possible: https://github.com/bazelbuild/rules_python/blob/master/proposals/2019-02-12-design-for-a-python-toolchain.md

**Comment by bshi** [comment] 2020-04-26 18:10
Isn't this a duplicate of https://github.com/bazelbuild/rules_python/issues/293?

**Comment by brandjon** [comment] 2020-05-12 21:50
#293 concerns creating a toolchain to represent a fetched Python interpreter. This issue seems to be talking about `PyRuntimeInfo`, which already exists (in native code) and is propagated by `py_runtime_pair`.

Feel free to reopen if I mischaracterized the request.

**Closed by brandjon** 2020-05-12 21:50 UTC
