### ISSUE TITLE
Bazel Failing on the latest version of numpy

### ISSUE THREAD

**Issue by stephenjones5543** [bazelbuild/rules_python#466] opened 2021-04-28 00:07 UTC
# 🐞 bug report
### Affected Rule

 The issue is caused by pip_install

### Is this a regression?

 No

### Description

Running ``` bazel run  //main:main``` at the  project root folder throws error.

## 🔬 Minimal Reproduction
I have tried to setup a tiny repo to replicate this issue, kindly [check it out here. ](https://github.com/stephenjones5543/bazel-test) 

## 🔥 Exception or Error
Please check the [error log output here](https://github.com/stephenjones5543/bazel-test/blob/main/main/output.log)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Big Sur Version 11.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jan 23 02:07:47 2021 (1611367667)
Build timestamp: 1611367667
Build timestamp as int: 1611367667
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
Using the SHA digest 0ab06a2d6cc5abca83d9c8a21d65630b773a079b
  </code>
</pre>

**Anything else relevant?**

**Comment by groodt** [comment] 2021-04-28 00:44
The issue is caused by a missing dependency. Your `requirements.txt` file is not "locked". It needs to list pinned versions of the full transitive dependency graph. The documentation about this in the docs is very poor @thundergolfer @alexeagle 

You can create such a file through an external tool at the moment (although there may be support for pip-tools being integrated into these rules in future).

This is mentioned in the docs:
```
You can generate this using pip-compile, or a virtualenv and pip freeze. pip_parse uses a label argument called requirements_lock instead of requirements to make this distinction clear.
```

These instructions apply to both approaches for using `requirements.txt`.

**Comment by thundergolfer** [comment] 2021-04-28 02:08
It shouldn't need to have a locked requirements file. After cloning your repo @stephenjones5543 and changing the requirements.txt file to just include these contents: 

```
# main/requirements.txt
numpy
```

and removing the long list of `requirment(...)` items in your target's `deps` list, I can `bazel run //main` and get:

```
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "917a154c3890c1e8f21c070280926454637cd290162f4ee6174877ce3566cc8b"
DEBUG: Repository rules_python instantiated at:
  /Users/jonathon/work/bazel-test/WORKSPACE:8:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_jonathon/8e9b9081fdb8de3f6c60f20491cdd3da/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //main:main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //main:main up-to-date:
  bazel-bin/main/main
INFO: Elapsed time: 0.129s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
2005-02-25
```

Which is expected successful output looking at `main.py`.

----

Now without making those changes, what I get when trying `bazel build //...` is this error: 

```
 13, in _pip_repository_impl
		fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed: Collecting numpy==1.20.2
  Using cached numpy-1.20.2-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
 (ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy==1.20.2 from https://files.pythonhosted.org/packages/5b/95/da16a3e28733eb6affa81f4114722788fe599cff90692961869df1cfd8b8/numpy-1.20.2-cp39-cp39-macosx_10_9_x86_64.whl#sha256=4703b9e937df83f5b6b7447ca5912b5f5f297aba45f91dbbbc63ff9278c7aa98 (from -r /Users/jonathon/work/bazel-test/main/requirements.txt (line 2)):
        Expected sha256 e9459f40244bb02b2f14f6af0cd0732791d72232bbb0dc4bab57ef88e75f6935
             Got        4703b9e937df83f5b6b7447ca5912b5f5f297aba45f91dbbbc63ff9278c7aa98

```

If I fix that sha error (and fix the `deps` list in the `BUILD` file) again `bazel run //main` succeeds.

---

The `deps` list you have in that `py_binary` target is not right for a reproduction of a `numpy` install issue. 

It includes many dependencies which are both:

1. Not a dependency of `numpy` and thus aren't available given a requirements.txt file that just lists `numpy` as a top-level dep.
2. Not a dependency of your application code. 

To run your `main.py` all that's required is: 

```python
load("@numpy_test_requirements//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        requirement("numpy"),
    ],
)
```

**Comment by thundergolfer** [comment] 2021-04-28 02:11
I'll close this issue because I can install `numpy` in your reproduction by fixing the mistakes in the `requirements.txt` (how was the incorrect hash produced?) and in the `BUILD` file. 👍

If those fixes (described above) don't sort out your installation issue please jump back in with further detail.

**Closed by thundergolfer** 2021-04-28 02:11 UTC
