### ISSUE TITLE
Describe how to make python envs with all targets for IDE integration

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_python#1661] opened 2024-01-02 16:48 UTC
# 🚀 feature request

### Relevant Rules

Unknown

### Description

I would like there to be a tool which is able to produce a valid venv such that IDEs can use it and resolve symbols for external python projects.

### Describe the solution you'd like

If I depend on an external repository `@third_party_dep//:dep`, I wanna be able to control+click in my IDE (vscode or something) an go to the symbol at `$(bazel info output_base)/external/third_party_dep/dep.py`.

### Describe alternatives you've considered

This is generally not an issue for `pypi` projects since I can make a venv from the list of requirements in my current workspace but I have no way to resolve bazel targets. So I know of no alternative.

**Comment by jvolkman** [comment] 2024-01-02 17:13
https://github.com/cedarai/rules_pyvenv does what you want. I believe https://github.com/aspect-build/rules_py does as well.

**Comment by UebelAndre** [comment] 2024-01-20 19:40
I don't think https://github.com/aspect-build/rules_py does this but https://github.com/cedarai/rules_pyvenv might be useful if there was other tooling to query and install pure bazel python targets and their dependencies. The issue is not that the `py_binary` targets do or do not create venvs. It's that creating a "mega-venv" that includes pure Bazel targets is not something I see an existing solution for.

**Comment by jvolkman** [comment] 2024-01-20 20:25
Maybe I don't understand what you mean by "pure Bazel targets", but `rules_pyvenv` will place any Bazel dep in the venv, not just those sourced from pip_install. For instance, if you have generated protobuf source, that gets placed in the venv so that code navigation works.

**Comment by groodt** [comment] 2024-09-21 10:40
Closing as duplicate of https://github.com/bazelbuild/rules_python/issues/1401

**Closed by groodt** 2024-09-21 10:40 UTC
