### ISSUE TITLE
python3_9_x86_64-unknown-linux-gnu/bin/python3: error while loading shared libraries: libcrypt.so.1

### ISSUE THREAD

**Issue by jmelahman** [bazelbuild/rules_python#716] opened 2022-05-29 10:52 UTC
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:  python_register_toolchains()

### Is this a regression?

Don't think so, but didn't confirm

## 🔬 Minimal Reproduction

https://github.com/jmelahman/playground/tree/arch-toolchain

## 🔥 Exception or Error

<pre><code>
$ ./repro.bash 
Unable to find image 'lahmanja/arch:v1.0.0' locally
v1.0.0: Pulling from lahmanja/arch
b65db44913f6: Pull complete 
beb98d5a80d3: Pull complete 
ef59f96cfb35: Pull complete 
93efd2a0e179: Pull complete 
73ede4e4f4e4: Pull complete 
3511e1da7f29: Pull complete 
Digest: sha256:7ec8b75098c5ed537e1c21953513bd81219b7951f387b0020d0e6f235eb2def1
Status: Downloaded newer image for lahmanja/arch:v1.0.0
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Repository my_deps instantiated at:
  /src/workspace/WORKSPACE:24:10: in <toplevel>
  /root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/rules_python/python/pip.bzl:206:19: in pip_parse
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/rules_python/python/pip_install/pip_repository.bzl:323:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'my_deps':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/rules_python/python/pip_install/pip_repository.bzl", line 195, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (/root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/python3_9_x86_64-unknown-linux-gnu/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
)
ERROR: /src/workspace/WORKSPACE:24:10: fetching pip_repository rule //external:my_deps: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/rules_python/python/pip_install/pip_repository.bzl", line 195, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (/root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/python3_9_x86_64-unknown-linux-gnu/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
)
ERROR: no such package '@my_deps//': rules_python failed:  (/root/.cache/bazel/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/python3_9_x86_64-unknown-linux-gnu/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
)
INFO: Elapsed time: 12.036s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

$ uname -a
Linux kyoko 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 5.1.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.8.1
  </code>
</pre>

**Anything else relevant?**
```
$ pacman -F libcrypt.so.1
core/libxcrypt-compat 4.4.28-2
    usr/lib/libcrypt.so.1
community/aarch64-linux-gnu-glibc 2.35-1
    usr/aarch64-linux-gnu/lib/libcrypt.so.1
community/riscv64-linux-gnu-glibc 2.32-1 (risc-v)
    usr/riscv64-linux-gnu/lib/libcrypt.so.1
```
Installing this [core/libxcrypt-compat](https://archlinux.org/packages/core/x86_64/libxcrypt-compat/) resolves the error

**Comment by groodt** [comment] 2022-05-31 07:52
This is an Arch Linux issue https://bbs.archlinux.org/viewtopic.php?id=274160

Your workaround is the correct solution. Arch Linux has moved to newer glibc versions so there will be many things in the python ecosystem that won't work without the compatibility package you've installed.

See: https://mayeut.github.io/manylinux-timeline/

**Comment by groodt** [comment] 2022-06-10 19:53
Are you happy to close this @jmelahman ? The issue is not with rules_python and your workaround seems sufficient.

**Comment by jmelahman** [comment] 2022-06-11 18:31
Makes sense to me. Thanks

**Closed** 2022-06-11 18:31 UTC
Labels: type: bug
