### ISSUE TITLE
Bzlmod rule python pip extension generated package path without dot.

### ISSUE THREAD

**Issue by bfsoyc** [bazelbuild/rules_python#1774] opened 2024-02-22 10:12 UTC
# 🚀 feature request

### Relevant Rules

pip extensions with bzlmod

### Description

I m migrating to  Bazel 7.0 release with Bzlmod feature.
Use the example in this repo to import pip dependancy.
The new dir tree of the generate site-package is in the pattern `rules_python~0.27.0~pip~pip_39_{package_name}`,
where I use rule_python of version 0.27.0 and register a python toolchain with 3.9.
As you can see there's a `dot` in the file path and the folder contains a __init__.py file which implies it's a python module.
We know it's bad for python. Some lint tool like `pylint` may fail to analysis them.
Is it possible to prevent dot in file path?

### Describe the solution you'd like

 replace `.` with '_'

I m not sure if I miss anything by design.

**Comment by aignas** [comment] 2024-02-27 09:18
That won't be possible because we don't control the naming here. With bazel 7.1 that should change though, could you try out the latest rc and check?

That said, the actual naming scheme is an implementation detail and is likely to change, so if you start depending on this in the extra tooling you write, it may very brittle.

Maybe I am missing something here, so please let me know.

**Comment by bfsoyc** [comment] 2024-02-28 12:39
I just look closer to the rules' source code. 
Seems python rule only specify the hub_name, while the prefix is generated by Bazel framework?
https://github.com/bazelbuild/rules_python/blob/4dcfd21b4a3f1e0ee3e10a8e42efed5ad635f5b2/python/private/bzlmod/pip.bzl#L242
I actually meet the same issue as https://github.com/bazelbuild/rules_python/issues/1575
As you mention, it's brittle to take advantage of the implementation detail. The change of the Bazel behavior may break some tools accidentally.
Since it is not a python rule's feature, please feel free to close it. @aignas . Thanks a lot.
However, I still need to dig deeper on issue 1575.

**Comment by aignas** [comment] 2024-02-28 15:11
Duplicate of #1575

**Closed by aignas** 2024-02-28 15:11 UTC
