### ISSUE TITLE
pip_import/pip_install doesn't support cross-compilation

### ISSUE THREAD

**Issue by jkammerl** [bazelbuild/rules_python#97] opened 2018-04-25 09:23 UTC
@mhlopko: pip_import/pip_install generates corresponding wheel packages that are always compiled for the host system architecture. Any cross-compilation toolchain specified within the CROSSTOOL configuration is ignored. It would be great if the selected CC compiler from CROSSTOOL could be set before executing "pip install".

**Comment by Globegitter** [comment] 2018-05-25 21:04
Just running into the same issue, building a distroless image that includes [pillow-simd](https://github.com/uploadcare/pillow-simd/) from my ubuntu 16.04 machine seems to be quite difficult, especially due to the differences in `libjpeg` and `libwebp` libraries. Would there be any possible workarounds for now, apart from using a different base images?

**Comment by thundergolfer** [comment] 2021-05-09 08:08
Will close as duplicate of https://github.com/bazelbuild/rules_python/issues/260. The linked issue has more discussion, and more recent discussion.

**Closed by thundergolfer** 2021-05-09 08:08 UTC
Labels: untriaged
