### ISSUE TITLE
Build workaround for module-level circular dependencies

### ISSUE THREAD

**Issue by joshgc** [bazelbuild/rules_python#1492] opened 2023-10-16 20:01 UTC
# 🚀 feature request
I propose adding a new rule that would allow us to merge different python 3rd party dependencies into a single target. 

### Relevant Rules
`requirement` from pip_parse & pip_install. Potentially also `entrypoint`

### Description
`pip` allows modules to have circular dependencies such as `poetry` and `poetry-plugin-exporter` see [here](https://github.com/python-poetry/poetry-plugin-export/issues/240). When using pip_parse and requirement, bazel produces a `py_library(name="pkg" ... )` for each of these third party modules which then list the other module as a dependency.

### Describe the solution you'd like
I propose, without knowing how easy it is, to add a new rule like `merged_requirement(a, b)`. This rule creates a new py_library that has all the srcs and deps of the two input modules. I think this most closely mirrors what those package maintainers intended "we used two different git repos, but you should always use our code at the same time."

### Describe alternatives you've considered
I've also pointed out the problem to these two specific package maintainers. Unfortunately a) its been known a while and theres no action and b) if pip allows it, the community will continue to let it happen.

Thank you for any future conversation!

**Comment by groodt** [comment] 2023-10-16 21:12
👋 This is a common request. Closing as duplicate of https://github.com/bazelbuild/rules_python/issues/1076

The current plans from the maintainers is to add `patch` support, which provides a capability to workaround circular dependencies (and various other packaging sins) without needing to make dramatic changes to the user facing API or introducing additional complexity to end-users or maintainers.

**Closed by groodt** 2023-10-16 21:12 UTC
