### ISSUE TITLE
xgboost dependency error

### ISSUE THREAD

**Issue by jschenxiaoyu** [bazelbuild/rules_python#104] opened 2018-05-31 08:09 UTC
I have added `xgboost` in my bazel project with `rules_python`.

After I build my project, there should be a `xgboost` directory in `pypi__xgboost_0_71` of my project's runfiles. But `xgboost` directory doesn't exist so I get the error `ImportError: No module named xgboost`.

I have also tried other versions of `xgboost` but it doesn't work.

**Comment by thundergolfer** [comment] 2021-04-28 04:12
At my company we had quite a bit of trouble support xgboost `0.9.0` because it doesn't ship a wheel. I'm testing `pip_install` on `xgboost==1.4.1` now, and get the following error: 

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jonathon/06afea7962d8da87f8909d6040da389c/execroot/data_science/bazel-out/darwin-fastbuild/bin/app/example/helloworld/helloworld.runfiles/pypi/pypi__xgboost/xgboost/compat.py", line 101, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jonathon/06afea7962d8da87f8909d6040da389c/execroot/data_science/bazel-out/darwin-fastbuild/bin/app/example/helloworld/helloworld.runfiles/data_science/app/example/helloworld/helloworld.py", line 16, in <module>
    import xgboost
  File "/private/var/tmp/_bazel_jonathon/06afea7962d8da87f8909d6040da389c/execroot/data_science/bazel-out/darwin-fastbuild/bin/app/example/helloworld/helloworld.runfiles/pypi/pypi__xgboost/xgboost/__init__.py", line 9, in <module>
    from .core import DMatrix, DeviceQuantileDMatrix, Booster
  File "/private/var/tmp/_bazel_jonathon/06afea7962d8da87f8909d6040da389c/execroot/data_science/bazel-out/darwin-fastbuild/bin/app/example/helloworld/helloworld.runfiles/pypi/pypi__xgboost/xgboost/core.py", line 23, in <module>
    from .compat import (STRING_TYPES, DataFrame, py_str, PANDAS_INSTALLED,
  File "/private/var/tmp/_bazel_jonathon/06afea7962d8da87f8909d6040da389c/execroot/data_science/bazel-out/darwin-fastbuild/bin/app/example/helloworld/helloworld.runfiles/pypi/pypi__xgboost/xgboost/compat.py", line 104, in <module>
    except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined
```

This is because `xgboost` is not listing `setuptools` as a dependency (maybe assuming its stdlib when it's not). This line of code is where the import is attempted: https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/compat.py#L102

Because my test Bazel workspace's Python setup is ~hermetic `setuptools` is not available and thus the error, but this is not a bug in the rules.

If I look under the hood in my Bazel workspace, `pip_install` generates this BUILD file for xgboost:

```python
package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

filegroup(
    name="whl",
    srcs=glob(["*.whl"]),
    data=["//pypi__numpy:whl","//pypi__scipy:whl"]
)

py_library(
    name = "pypi__xgboost",
    srcs = glob(["**/*.py"], allow_empty = True),
    data = glob(["**/*"], exclude=["*.whl", "**/*.py", "**/* *", "BUILD.bazel", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = ["//pypi__numpy","//pypi__scipy"],
)
```

You can see `deps` doesn't include `setuptools` but xgboost's `compat.py` tries to use it. 

----

Closing issue as not an issue with rules_python anymore.

**Closed by thundergolfer** 2021-04-28 04:12 UTC
Labels: Can Close?, untriaged
