### ISSUE TITLE
Using a Python Package with 'console_scripts'

### ISSUE THREAD

**Issue by amit-traiana** [bazelbuild/rules_python#318] opened 2020-05-26 19:08 UTC
Hi,

I have a Python package that generate console script as entry-point. The `setup.py` looks like so:

``` 
entry_points={"console_scripts": ["my_package" = "my_package.cli:main"]}
```

I would like to call this python command line script from within a `gen_rule`, but unable to do it just by calling `my_package` directly. What I currently do, is to install the package with the requirements file, and create a `py_binary` like so:

```
    native.py_binary(
          name = "my_package",
          main = "__main__.py",
          srcs = [
              requirement("my_package"),
          ],
       deps = [
              requirement("pyyaml"),
       ],
    )
```

This works and I can consume the it from within `gen_rule`, but it feels a bit hacky - especially the part where I need to manually add deps and not use the deps defined in `setup.py`. 

Is there's a better way doing it perhaps?

**Comment by amitz** [comment] 2020-08-18 12:45
Seemed to be solved. I'm able to call console script directly from `gen_rule` (make sure you have the symbolic link in your path).

**Comment by thundergolfer** [comment] 2020-08-31 13:31
@amitz Are you able to provide an example, and more detail (particularly about "make sure you have the symbolic link...")?

**Comment by amitz** [comment] 2020-08-31 13:56
Yes, of-course. I'm using `pip_import` to install my package using `requirements.txt` file:

```
my_script==1.0
```

I then wrap it using a Bazel macro: 

```
def my_macro(name, **kwargs):
    native.genrule(
        name = name,
        srcs = [":infile.xml"],
        outs = ["outfile.xml"],
        cmd = "my_script --infile=$(location :infile.yaml) --outfile=$@",
    )
```

The `my_script` "binary" (Bash script calling the Python code) will be installed somewhere. What I missed is that multiple Docker containers will have different places to store that "binary". On some container It was `/usr/local/bin` on other `/usr/.local/bin` etc. So instead - I'm running Bazel in the context of a Virtual env - so the "binary" is always installed on the same spot. Make sure this spot is on your PATH.

**Comment by pstradomski** [comment] 2020-08-31 14:25
This suggests you're not really using the version installed by pip_import,
but the external version in your outer virtualenv (or in user instal
location)


-- 
Paweł Stradomski

**Comment by amitz** [comment] 2020-08-31 14:30
You right - It's also installed it on the outer virtualenv! In that case, I guess wrapping your script into `py_binary` is still mandatory action.

**Comment by thundergolfer** [comment] 2021-02-03 03:14
@amitz I'll close this as duplicate of https://github.com/bazelbuild/rules_python/issues/341. If you think the issues are clearly distinct, just jump back in here 👍

**Closed by thundergolfer** 2021-02-03 03:14 UTC
