### ISSUE TITLE
rules_python red on bazel ci

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_python#80] opened 2018-03-23 12:34 UTC
Rules_python are [red](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/174#f5eb9d93-aa0e-4788-a1f8-990c7c3b4d5e) on bazel ci for a while, it seems like commit 3175797bd07aac4ff35fa711f0a82285f2005e42 introduced a test that was never green? Is there a way to fix the world so the build is green?

Example build:
https://storage.googleapis.com/bazel-buildkite-artifacts/f5eb9d93-aa0e-4788-a1f8-990c7c3b4d5e/tools/par_test/attempt_1.log

Thanks!

**Comment by buchgr** [comment] 2018-03-23 12:51
Duplicate of https://github.com/bazelbuild/rules_python/issues/67

**Closed by buchgr** 2018-03-23 12:51 UTC
